dist: bionic
addons:
  apt: 
    packages:
      - beanstalkd
services:
  - postgresql
language: python
before_script:
  - psql -c 'create database www2png;' -U postgres
  - psql -U postgres -w -d www2png -f dev/sql/create_tables.sql
  - psql -U postgres -w -d www2png -f dev/test/data.sql
  - cp dev/test/.env.travis .env
script:
  - python -m unittest discover src
