import os
import smtplib, ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

def send_api_request_email(smtp_receiver, challenge):
	smtp_sender = os.getenv("SMTP_SENDER")
	smtp_host = os.getenv("SMTP_HOST")
	smtp_port = int(os.getenv("SMTP_PORT"))
	smtp_user = os.getenv("SMTP_USER")
	smtp_pass = os.getenv("SMTP_PASS")

	message = MIMEMultipart("alternative")
	message["Subject"] = "Your API Key"
	message["From"] = smtp_sender
	message["To"] = smtp_receiver

	message_text = f"Your API Key is: {challenge}\n\n"
	message_text += f"Please open the following URL to activate your API Key: {os.getenv('WWW2PNG_BASE_URL')}/api/activate/{challenge}\n\n"
	message_text += "Activating this key will deactivate any previous key associated with this email address.\n\n"
	message_text += f"For help, check out the API Help page: {os.getenv('WWW2PNG_BASE_URL')}/api/help\n\n"
	message_text += "This email was generated by a user on www2png.com. If you did not request an API key you can ignore this message."

	message.attach(MIMEText(message_text, "plain"))

	try:
		context = ssl.create_default_context()
		server = smtplib.SMTP(smtp_host, smtp_port)
		server.starttls(context=context)
		server.login(smtp_user, smtp_pass)
		server.sendmail(smtp_sender, smtp_receiver, message.as_string())
	except Exception as e:
		raise e
	finally:
		server.quit()
